apiVersion: v1
kind: ConfigMap
metadata:
  name: educhat-config
  namespace: dev
data:
  # Frontend
  VUEJS_PORT: "5173"

  # Backend
  FASTAPI_HOST: "edu-fastapi-host"
  FASTAPI_PORT: "8000"

  # Redis
  REDIS_HOST: "edu-redis-host"
  REDIS_PORT: "6379"

  # PostgreSQL
  POSTGRES_HOST: "edu-pg-host"
  POSTGRES_DB: "educhat_db"
  POSTGRES_PORT: "5432"

  PLAYWRIGHT_REDIS_HOST: "edu-redis-host"
  PLAYWRIGHT_PG_HOST: "edu-pg-host"
