apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-redis
  labels:
    app: &app-name redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *app-name
  template:
    metadata:
      name: *app-name
      labels:
        app: *app-name
    spec:
      containers:
        - name: *app-name
          image: redis/redis-stack-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: educhat-config
            - secretRef:
                name: educhat-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
      