apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
  labels:
    app: &appName fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *appName
  template:
    metadata:
      labels:
        app: *appName
    spec:
      containers:
        - name: *appName
          image: ghcr.io/0xcaf3d0od/edu-backend:sha256-32ce3795f74637f2e88bd9dfa1cf5dec78ee090bdf0f0446309e424f6b20c4d4
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: educhat-config
            - secretRef:
                name: educhat-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
