# =====================
# GLOBAL
# =====================
namespace: dev

app:
  name: edu

# =====================
# INGRESS
# =====================
ingress:
  className: traefik

# =====================
# DEPLOYMENT NAMES
# =====================
deployments:
  backend: deployment-backend
  frontend: deployment-frontend
  postgres: deployment-postgres
  redis: deployment-redis


# =====================
# SERVICES NAMES (source de vérité unique)
# =====================
services:
  backend: service-backend
  frontend: service-frontend
  postgres: service-postgres
  redis: service-redis

# =====================
# PORTS
# =====================
ports:
  backend: 8000
  frontend: 5173
  postgres: 5432
  redis: 6379
  ingress: 80

# =====================
# IMAGES
# =====================
images:
  backend: ghcr.io/0xcaf3d0od/edu-backend:latest
  frontend: ghcr.io/0xcaf3d0od/edu-frontend:latest
  postgres: ghcr.io/0xcaf3d0od/edu-database:latest
  redis: redis:latest

# =====================
# REPLICAS
# =====================
replicas:
  backend: 2
  frontend: 1
  postgres: 1
  redis: 1

# =====================
# CONFIG (remplace app-config.yaml)
# =====================
config:
  postgres:
    db: educhat-db
  app:
    configMap: educhat-config
    secrets: educhat-secret

# =====================
# RESOURCES COMPUTE
# =====================
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m