apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.app.secrets }}"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.secrets.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres.password }}"