apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.config.app.configMap }}"
  namespace: {{ .Values.namespace }}
data:
  # Frontend
  VUEJS_PORT: "{{ .Values.ports.frontend }}"

  # Backend
  FASTAPI_HOST: "{{ .Values.services.backend }}"
  FASTAPI_PORT: "{{ .Values.ports.backend }}"

  # Redis
  REDIS_HOST: "{{ .Values.services.redis }}"
  REDIS_PORT: "{{ .Values.ports.redis }}"

  # PostgreSQL
  POSTGRES_HOST: "{{ .Values.services.postgres }}"
  POSTGRES_DB: "{{ .Values.config.postgres }}"
  POSTGRES_PORT: "{{ .Values.ports.postgres }}"

  PLAYWRIGHT_REDIS_HOST: "{{ .Values.services.redis }}"
  PLAYWRIGHT_POSTGRES_HOST: "{{ .Values.services.postgres }}"
