apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.app.secrets }}"
  namespace: {{ .Values.namespace }}
type: Opaque
# Secret data → Kubernetes décode le base64 avant de l'injecter dans le container
# Si data au lieu de stringData; user doit encoder en base64; stringData permet d'utiliser du text plain.
stringData:
  POSTGRES_USER: "{{ .Values.secrets.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres.password }}"