apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.config.app.configMap }}"
  namespace: {{ .Values.namespace }}
# ConfigMap data → Kubernetes stocke la valeur telle quelle
# Stocke des données en texte plain.
# Kubernetes ne fait aucune transformation: donc data
data:
  # Frontend
  VUEJS_PORT: "{{ .Values.ports.frontend }}"

  # Backend
  FASTAPI_HOST: "{{ .Values.app.name }}-{{ .Values.services.backend }}"
  FASTAPI_PORT: "{{ .Values.ports.backend }}"

  # Redis
  REDIS_HOST: "{{ .Values.app.name }}-{{ .Values.services.redis }}"
  REDIS_PORT: "{{ .Values.ports.redis }}"

  # PostgreSQL
  POSTGRES_HOST: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
  POSTGRES_DB: "{{ .Values.config.postgres.db }}"
  POSTGRES_PORT: "{{ .Values.ports.postgres }}"

  PLAYWRIGHT_REDIS_HOST: "{{ .Values.app.name }}-{{ .Values.services.redis }}"
  PLAYWRIGHT_POSTGRES_HOST: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
