apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-redis
  namespace: dev
  labels:
    app: &appName redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *appName
  template:
    metadata:
      name: *appName
      labels:
        app: *appName
    spec:
      containers:
        - name: *appName
          image: redis/redis-stack-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          envFrom:
            - configMapRef:
                name: educhat-config
            - secretRef:
                name: educhat-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
      