apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
  labels:
    app: &appName Vue-vite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *appName
  template:
    metadata:
      labels:
        app: *appName
    spec:
      containers:
        - name: *appName
          image: ghcr.io/0xcaf3d0od/edu-frontend:sha256-2b0848044acc83fd934409a02b7bd96cf579073a7053546d298585135d8063bc
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: educhat-config
            - secretRef:
                name: educhat-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
