apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.deployments.postgres }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
spec:
  replicas: {{ .Values.replicas.postgres }}
  # - PostgreSQL n'est pas conçu pour scaler horizontalement.
  # - Lancer 2 replicas qui écrivent sur le même volume = corruption de données.
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
    spec:
      containers:
        - name: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
          image: "{{ .Values.images.postgres }}"
          ports:
            - containerPort: {{ .Values.ports.postgres }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ .Values.config.app.configMap }}"
            - secretRef:
                name: "{{ .Values.config.app.secrets }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

