apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: dev
  labels:
    app: &appName postgres
spec:
  replicas: 1
  # - PostgreSQL n'est pas conçu pour scaler horizontalement.
  # - Lancer 2 replicas qui écrivent sur le même volume = corruption de données.
  selector:
    matchLabels:
      app: *appName
  template:
    metadata:
      labels:
        app: *appName
    spec:
      containers:
        - name: *appName
          image: ghcr.io/0xcaf3d0od/edu-database:sha256-de7c83833408670e87209ac84e207a4cc0a0ad37108a5f05d134b76740eaffb3
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: educhat-config
            - secretRef:
                name: educhat-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

