apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.deployments.frontend }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.app.name }}-{{ .Values.services.frontend }}"
spec:
  replicas: {{ .Values.replicas.frontend }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}-{{ .Values.services.frontend }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}-{{ .Values.services.frontend }}"
    spec:
      containers:
        - name: "{{ .Values.app.name }}-{{ .Values.services.frontend }}"
          image: "{{ .Values.images.frontend }}"
          ports:
            - containerPort: {{ .Values.ports.frontend }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ .Values.config.app.configMap }}"
            - secretRef:
                name: "{{ .Values.config.app.secrets }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}