apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: edu-ingress
                port:
                  number: 80
