apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
  ports:
    - protocol: TCP
      port: {{ .Values.ports.postgres }}
      targetPort: {{ .Values.ports.postgres }}
  type: ClusterIP
  