apiVersion: v1
kind: Service
metadata:
  name: edu-service-backend
spec:
  selector:
    app: edu-service-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
  