apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
spec:
  selector:
    app: "{{ .Values.app.name }}-{{ .Values.services.postgres }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
  type: NodePort
  