version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb-dk
      MYSQL_USER: username
      MYSQL_PASSWORD: userpswd
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysqldb
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: userpswd
      WORDPRESS_DB_NAME: mysqldb-dk
    volumes:
      - wordpress_data:/var/www/html
#    ports:
#      - "9000:9000"
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: root
      PMA_ABSOLUTE_URI: https://20.160.158.48/phpma/
    networks:
      - wordpress-network

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/adminuser/ssl:/etc/nginx/ssl:ro
      - wordpress_data:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  mysql_data:
  wordpress_data:
  phpmyadmin_data: