# https://blog.stephane-robert.info/docs/infra-as-code/gestion-de-configuration/ansible/premiers-pas/premier-playbook/#:~:text=Les%20cl%C3%A9s%20essentielles%20d%27un%20play%20%3A
- name: Install K3S in VM's
  hosts: all
  become: true

  roles:
    - xanmanning.k3s

  tasks:
    - name: Ensure k3s is installed
      ansible.builtin.service:
        name: k3s
        state: started
        enabled: yes
      tags: k3s

    # Source - https://stackoverflow.com/a/76181866
    # Posted by Sergey Kalikin, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-05-27, License - CC BY-SA 4.0
    # ---
    - name: Download Helm command line tool
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        return_content: true
      register: helm_installer
      tags: helm

    - name: Install Helm
      ansible.builtin.command:
        cmd: bash
        stdin: "{{ helm_installer.content }}"
        creates: /usr/local/bin/helm
      environment:
        DESIRED_VERSION: "{{ helm_version | default('') }}"
      tags: helm
